// Package crosspay provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package crosspay

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for TenantEntitlementEntitlementType.
const (
	Consumable    TenantEntitlementEntitlementType = "consumable"
	NonConsumable TenantEntitlementEntitlementType = "non_consumable"
	Subscription  TenantEntitlementEntitlementType = "subscription"
)

// Valid indicates whether the value is a known member of the TenantEntitlementEntitlementType enum.
func (e TenantEntitlementEntitlementType) Valid() bool {
	switch e {
	case Consumable:
		return true
	case NonConsumable:
		return true
	case Subscription:
		return true
	default:
		return false
	}
}

// CustomerEntitlement defines model for CustomerEntitlement.
type CustomerEntitlement struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// CustomerEntitlements defines model for CustomerEntitlements.
type CustomerEntitlements struct {
	CustomerId    string              `json:"customer_id"`
	Email         string              `json:"email"`
	Purchases     *[]PurchaseItem     `json:"purchases"`
	Subscriptions *[]SubscriptionItem `json:"subscriptions"`
}

// CustomerListItem defines model for CustomerListItem.
type CustomerListItem struct {
	CustomerId   string                 `json:"customer_id"`
	Email        string                 `json:"email"`
	Entitlements *[]CustomerEntitlement `json:"entitlements"`
	Products     *[]CustomerProduct     `json:"products"`
	Status       string                 `json:"status"`
}

// CustomerProduct defines model for CustomerProduct.
type CustomerProduct struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// GetCustomerExtendedInfoByEmailRow defines model for GetCustomerExtendedInfoByEmailRow.
type GetCustomerExtendedInfoByEmailRow struct {
	Email           string  `json:"email"`
	EmailSha256Sum  *string `json:"email_sha256_sum"`
	EntitlementName *string `json:"entitlement_name"`
	EntitlementType *string `json:"entitlement_type"`
	Id              string  `json:"id"`
	ProductId       *string `json:"product_id"`
	ProductName     *string `json:"product_name"`
	Status          *string `json:"status"`
	Store           *string `json:"store"`
}

// ListCustomerResponseBody defines model for ListCustomerResponseBody.
type ListCustomerResponseBody struct {
	Data  PaginatedCustomers `json:"data"`
	Error *string            `json:"error,omitempty"`
}

// PaginatedCustomers defines model for PaginatedCustomers.
type PaginatedCustomers struct {
	Customers  *[]CustomerListItem `json:"customers"`
	Limit      int64               `json:"limit"`
	NextCursor *string             `json:"next_cursor,omitempty"`
	Total      *int64              `json:"total,omitempty"`
}

// PurchaseItem defines model for PurchaseItem.
type PurchaseItem struct {
	EntitlementId   string `json:"entitlement_id"`
	EntitlementName string `json:"entitlement_name"`
	EntitlementType string `json:"entitlement_type"`
	ProductId       string `json:"product_id"`
	ProductName     string `json:"product_name"`
	PurchaseState   string `json:"purchase_state"`
	Status          string `json:"status"`
	Store           string `json:"store"`
}

// StorableEntitlement defines model for StorableEntitlement.
type StorableEntitlement struct {
	EntitlementId   string  `json:"entitlement_id"`
	EntitlementType string  `json:"entitlement_type"`
	ExpiresAt       int64   `json:"expires_at"`
	Id              string  `json:"id"`
	ProductId       string  `json:"product_id"`
	PurchaseState   *string `json:"purchase_state,omitempty"`
	RenewalStatus   string  `json:"renewal_status"`
	Status          string  `json:"status"`
	Store           string  `json:"store"`
	TrialExpiresAt  *int64  `json:"trial_expires_at"`
}

// StorableSubscription defines model for StorableSubscription.
type StorableSubscription struct {
	EntitlementId  string `json:"entitlement_id"`
	ExpiresAt      int64  `json:"expires_at"`
	Id             string `json:"id"`
	ProductId      string `json:"product_id"`
	RenewalStatus  string `json:"renewal_status"`
	Status         string `json:"status"`
	Store          string `json:"store"`
	TrialExpiresAt *int64 `json:"trial_expires_at"`
}

// SubscriptionItem defines model for SubscriptionItem.
type SubscriptionItem struct {
	EntitlementId   string `json:"entitlement_id"`
	EntitlementName string `json:"entitlement_name"`
	EntitlementType string `json:"entitlement_type"`
	ProductId       string `json:"product_id"`
	ProductName     string `json:"product_name"`
	Status          string `json:"status"`
	Store           string `json:"store"`
}

// SubscriptionStripePrice defines model for SubscriptionStripePrice.
type SubscriptionStripePrice struct {
	Currency       string `json:"currency"`
	FormattedPrice string `json:"formattedPrice"`
	Id             string `json:"id"`
	Price          int32  `json:"price"`
	UnitLabel      string `json:"unitLabel"`
}

// SubscriptionStripeProduct defines model for SubscriptionStripeProduct.
type SubscriptionStripeProduct struct {
	Active              bool                    `json:"active"`
	Created             int64                   `json:"created"`
	Deleted             *bool                   `json:"deleted,omitempty"`
	Description         *string                 `json:"description,omitempty"`
	Id                  string                  `json:"id"`
	Images              *[]string               `json:"images"`
	Livemode            bool                    `json:"livemode"`
	Metadata            map[string]string       `json:"metadata"`
	Name                string                  `json:"name"`
	Object              string                  `json:"object"`
	Price               SubscriptionStripePrice `json:"price"`
	Shippable           *bool                   `json:"shippable,omitempty"`
	StatementDescriptor *string                 `json:"statement_descriptor,omitempty"`
	Type                string                  `json:"type"`
	UnitLabel           *string                 `json:"unit_label,omitempty"`
	Updated             int64                   `json:"updated"`
	Url                 *string                 `json:"url,omitempty"`
}

// TenantActiveEntitlementsInputBody defines model for TenantActiveEntitlementsInputBody.
type TenantActiveEntitlementsInputBody struct {
	CustomerEmail string  `json:"customer_email"`
	Environment   *string `json:"environment"`
}

// TenantActiveEntitlementsResponseBody defines model for TenantActiveEntitlementsResponseBody.
type TenantActiveEntitlementsResponseBody struct {
	Data  *[]StorableEntitlement `json:"data,omitempty"`
	Error *string                `json:"error,omitempty"`
}

// TenantActiveSubscriptionInputBody defines model for TenantActiveSubscriptionInputBody.
type TenantActiveSubscriptionInputBody struct {
	CustomerEmail string  `json:"customer_email"`
	Environment   *string `json:"environment"`
}

// TenantActiveSubscriptionResponseBody defines model for TenantActiveSubscriptionResponseBody.
type TenantActiveSubscriptionResponseBody struct {
	Data  *StorableSubscription `json:"data,omitempty"`
	Error *string               `json:"error,omitempty"`
}

// TenantCancelGoCardlessSubscriptionInputBody defines model for TenantCancelGoCardlessSubscriptionInputBody.
type TenantCancelGoCardlessSubscriptionInputBody struct {
	CustomerEmail string `json:"customer_email"`
	EntitlementId string `json:"entitlement_id"`
}

// TenantCancelGoCardlessSubscriptionResponseBody defines model for TenantCancelGoCardlessSubscriptionResponseBody.
type TenantCancelGoCardlessSubscriptionResponseBody struct {
	Error *string `json:"error,omitempty"`
}

// TenantCancelStripeSubscriptionInputBody defines model for TenantCancelStripeSubscriptionInputBody.
type TenantCancelStripeSubscriptionInputBody struct {
	CustomerEmail string `json:"customer_email"`
	EntitlementId string `json:"entitlement_id"`
}

// TenantCancelStripeSubscriptionResponseBody defines model for TenantCancelStripeSubscriptionResponseBody.
type TenantCancelStripeSubscriptionResponseBody struct {
	Error *string `json:"error,omitempty"`
}

// TenantEntitlement defines model for TenantEntitlement.
type TenantEntitlement struct {
	Description     *string                          `json:"description"`
	EntitlementType TenantEntitlementEntitlementType `json:"entitlement_type"`
	Id              string                           `json:"id"`
	Metadata        []byte                           `json:"metadata"`
	Name            string                           `json:"name"`
	PeriodMs        int64                            `json:"period_ms"`
	Products        TenantProducts                   `json:"products"`
}

// TenantEntitlementEntitlementType defines model for TenantEntitlement.EntitlementType.
type TenantEntitlementEntitlementType string

// TenantEntitlementProduct defines model for TenantEntitlementProduct.
type TenantEntitlementProduct struct {
	Description *string `json:"description"`
	Id          string  `json:"id"`
	Metadata    []byte  `json:"metadata"`
	Name        string  `json:"name"`
	ProductId   string  `json:"product_id"`
}

// TenantGoCardlessBillingRequestFlowInputBody defines model for TenantGoCardlessBillingRequestFlowInputBody.
type TenantGoCardlessBillingRequestFlowInputBody struct {
	CustomerEmail      string `json:"customer_email"`
	FailureRedirectUrl string `json:"failure_redirect_url"`
	ProductId          string `json:"product_id"`
	RedirectUrl        string `json:"redirect_url"`
}

// TenantGoCardlessBillingRequestFlowResponseBody defines model for TenantGoCardlessBillingRequestFlowResponseBody.
type TenantGoCardlessBillingRequestFlowResponseBody struct {
	Error *string `json:"error,omitempty"`
	Url   string  `json:"url"`
}

// TenantIdentifyUserInputBody defines model for TenantIdentifyUserInputBody.
type TenantIdentifyUserInputBody struct {
	CustomerEmail string `json:"customer_email"`
}

// TenantIdentifyUserResponseBody defines model for TenantIdentifyUserResponseBody.
type TenantIdentifyUserResponseBody struct {
	CustomerId *string `json:"customer_id,omitempty"`
	Error      *string `json:"error,omitempty"`
}

// TenantListEntitlementsResponseBody defines model for TenantListEntitlementsResponseBody.
type TenantListEntitlementsResponseBody struct {
	Data  *[]TenantEntitlement `json:"data"`
	Error *string              `json:"error,omitempty"`
}

// TenantListProductsResponseBody defines model for TenantListProductsResponseBody.
type TenantListProductsResponseBody struct {
	Data  *[]TenantProduct `json:"data"`
	Error *string          `json:"error,omitempty"`
}

// TenantListStripeProductsResponseBody defines model for TenantListStripeProductsResponseBody.
type TenantListStripeProductsResponseBody struct {
	Data  *[]SubscriptionStripeProduct `json:"data"`
	Error *string                      `json:"error,omitempty"`
}

// TenantProduct defines model for TenantProduct.
type TenantProduct struct {
	Description   *string `json:"description"`
	EntitlementId string  `json:"entitlement_id"`
	Id            string  `json:"id"`
	Metadata      []byte  `json:"metadata"`
	Name          string  `json:"name"`
	ProductId     string  `json:"product_id"`
	Store         string  `json:"store"`
}

// TenantProducts defines model for TenantProducts.
type TenantProducts struct {
	Appstore   TenantEntitlementProduct `json:"appstore"`
	Gocardless TenantEntitlementProduct `json:"gocardless"`
	Playstore  TenantEntitlementProduct `json:"playstore"`
	Stripe     TenantEntitlementProduct `json:"stripe"`
}

// TenantServerGetCustomerInputBody defines model for TenantServerGetCustomerInputBody.
type TenantServerGetCustomerInputBody struct {
	CustomerEmail string  `json:"customer_email"`
	Environment   *string `json:"environment"`
}

// TenantServerGetCustomerResponseBody defines model for TenantServerGetCustomerResponseBody.
type TenantServerGetCustomerResponseBody struct {
	Data  *GetCustomerExtendedInfoByEmailRow `json:"data,omitempty"`
	Error *string                            `json:"error,omitempty"`
}

// TenantServerGetCustomerV2ResponseBody defines model for TenantServerGetCustomerV2ResponseBody.
type TenantServerGetCustomerV2ResponseBody struct {
	Data  *CustomerEntitlements `json:"data,omitempty"`
	Error *string               `json:"error,omitempty"`
}

// TenantStripeCheckoutInputBody defines model for TenantStripeCheckoutInputBody.
type TenantStripeCheckoutInputBody struct {
	CustomerEmail      string `json:"customer_email"`
	FailureRedirectUrl string `json:"failure_redirect_url"`
	ProductId          string `json:"product_id"`
	RedirectUrl        string `json:"redirect_url"`
}

// TenantStripeCheckoutResponseBody defines model for TenantStripeCheckoutResponseBody.
type TenantStripeCheckoutResponseBody struct {
	Error *string `json:"error,omitempty"`
	Url   string  `json:"url"`
}

// GetTenantServerCustomersParams defines parameters for GetTenantServerCustomers.
type GetTenantServerCustomersParams struct {
	Limit  *int64  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetTenantProductsParams defines parameters for GetTenantProducts.
type GetTenantProductsParams struct {
	ApiKey *string `json:"api-key,omitempty"`
}

// PostTenantServerCustomerJSONRequestBody defines body for PostTenantServerCustomer for application/json ContentType.
type PostTenantServerCustomerJSONRequestBody = TenantServerGetCustomerInputBody

// PostTenantServerGocardlessCancelByEnvironmentJSONRequestBody defines body for PostTenantServerGocardlessCancelByEnvironment for application/json ContentType.
type PostTenantServerGocardlessCancelByEnvironmentJSONRequestBody = TenantCancelGoCardlessSubscriptionInputBody

// PostTenantServerStripeCancelByEnvironmentJSONRequestBody defines body for PostTenantServerStripeCancelByEnvironment for application/json ContentType.
type PostTenantServerStripeCancelByEnvironmentJSONRequestBody = TenantCancelStripeSubscriptionInputBody

// PostTenantServerV2CustomerJSONRequestBody defines body for PostTenantServerV2Customer for application/json ContentType.
type PostTenantServerV2CustomerJSONRequestBody = TenantServerGetCustomerInputBody

// PostTenantEntitlementsActiveJSONRequestBody defines body for PostTenantEntitlementsActive for application/json ContentType.
type PostTenantEntitlementsActiveJSONRequestBody = TenantActiveEntitlementsInputBody

// PostTenantGocardlessBillingRequestFlowByEnvironmentJSONRequestBody defines body for PostTenantGocardlessBillingRequestFlowByEnvironment for application/json ContentType.
type PostTenantGocardlessBillingRequestFlowByEnvironmentJSONRequestBody = TenantGoCardlessBillingRequestFlowInputBody

// PostTenantIdentifyJSONRequestBody defines body for PostTenantIdentify for application/json ContentType.
type PostTenantIdentifyJSONRequestBody = TenantIdentifyUserInputBody

// PostTenantStripeCheckoutByEnvironmentJSONRequestBody defines body for PostTenantStripeCheckoutByEnvironment for application/json ContentType.
type PostTenantStripeCheckoutByEnvironmentJSONRequestBody = TenantStripeCheckoutInputBody

// PostTenantSubscriptionsActiveJSONRequestBody defines body for PostTenantSubscriptionsActive for application/json ContentType.
type PostTenantSubscriptionsActiveJSONRequestBody = TenantActiveSubscriptionInputBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostTenantServerCustomerWithBody request with any body
	PostTenantServerCustomerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTenantServerCustomer(ctx context.Context, body PostTenantServerCustomerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTenantServerCustomers request
	GetTenantServerCustomers(ctx context.Context, params *GetTenantServerCustomersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTenantServerGocardlessCancelByEnvironmentWithBody request with any body
	PostTenantServerGocardlessCancelByEnvironmentWithBody(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTenantServerGocardlessCancelByEnvironment(ctx context.Context, environment string, body PostTenantServerGocardlessCancelByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTenantServerStripeCancelByEnvironmentWithBody request with any body
	PostTenantServerStripeCancelByEnvironmentWithBody(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTenantServerStripeCancelByEnvironment(ctx context.Context, environment string, body PostTenantServerStripeCancelByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTenantServerV2CustomerWithBody request with any body
	PostTenantServerV2CustomerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTenantServerV2Customer(ctx context.Context, body PostTenantServerV2CustomerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTenantEntitlementsActiveWithBody request with any body
	PostTenantEntitlementsActiveWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTenantEntitlementsActive(ctx context.Context, body PostTenantEntitlementsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTenantEntitlementsByEnvironment request
	GetTenantEntitlementsByEnvironment(ctx context.Context, environment string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTenantGocardlessBillingRequestFlowByEnvironmentWithBody request with any body
	PostTenantGocardlessBillingRequestFlowByEnvironmentWithBody(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTenantGocardlessBillingRequestFlowByEnvironment(ctx context.Context, environment string, body PostTenantGocardlessBillingRequestFlowByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTenantIdentifyWithBody request with any body
	PostTenantIdentifyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTenantIdentify(ctx context.Context, body PostTenantIdentifyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTenantProducts request
	GetTenantProducts(ctx context.Context, params *GetTenantProductsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTenantStripeCheckoutByEnvironmentWithBody request with any body
	PostTenantStripeCheckoutByEnvironmentWithBody(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTenantStripeCheckoutByEnvironment(ctx context.Context, environment string, body PostTenantStripeCheckoutByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTenantStripeProductsByEnvironment request
	GetTenantStripeProductsByEnvironment(ctx context.Context, environment string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTenantSubscriptionsActiveWithBody request with any body
	PostTenantSubscriptionsActiveWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTenantSubscriptionsActive(ctx context.Context, body PostTenantSubscriptionsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostTenantServerCustomerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantServerCustomerRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantServerCustomer(ctx context.Context, body PostTenantServerCustomerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantServerCustomerRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTenantServerCustomers(ctx context.Context, params *GetTenantServerCustomersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTenantServerCustomersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantServerGocardlessCancelByEnvironmentWithBody(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantServerGocardlessCancelByEnvironmentRequestWithBody(c.Server, environment, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantServerGocardlessCancelByEnvironment(ctx context.Context, environment string, body PostTenantServerGocardlessCancelByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantServerGocardlessCancelByEnvironmentRequest(c.Server, environment, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantServerStripeCancelByEnvironmentWithBody(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantServerStripeCancelByEnvironmentRequestWithBody(c.Server, environment, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantServerStripeCancelByEnvironment(ctx context.Context, environment string, body PostTenantServerStripeCancelByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantServerStripeCancelByEnvironmentRequest(c.Server, environment, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantServerV2CustomerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantServerV2CustomerRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantServerV2Customer(ctx context.Context, body PostTenantServerV2CustomerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantServerV2CustomerRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantEntitlementsActiveWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantEntitlementsActiveRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantEntitlementsActive(ctx context.Context, body PostTenantEntitlementsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantEntitlementsActiveRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTenantEntitlementsByEnvironment(ctx context.Context, environment string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTenantEntitlementsByEnvironmentRequest(c.Server, environment)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantGocardlessBillingRequestFlowByEnvironmentWithBody(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantGocardlessBillingRequestFlowByEnvironmentRequestWithBody(c.Server, environment, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantGocardlessBillingRequestFlowByEnvironment(ctx context.Context, environment string, body PostTenantGocardlessBillingRequestFlowByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantGocardlessBillingRequestFlowByEnvironmentRequest(c.Server, environment, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantIdentifyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantIdentifyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantIdentify(ctx context.Context, body PostTenantIdentifyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantIdentifyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTenantProducts(ctx context.Context, params *GetTenantProductsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTenantProductsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantStripeCheckoutByEnvironmentWithBody(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantStripeCheckoutByEnvironmentRequestWithBody(c.Server, environment, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantStripeCheckoutByEnvironment(ctx context.Context, environment string, body PostTenantStripeCheckoutByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantStripeCheckoutByEnvironmentRequest(c.Server, environment, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTenantStripeProductsByEnvironment(ctx context.Context, environment string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTenantStripeProductsByEnvironmentRequest(c.Server, environment)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantSubscriptionsActiveWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantSubscriptionsActiveRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantSubscriptionsActive(ctx context.Context, body PostTenantSubscriptionsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantSubscriptionsActiveRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostTenantServerCustomerRequest calls the generic PostTenantServerCustomer builder with application/json body
func NewPostTenantServerCustomerRequest(server string, body PostTenantServerCustomerJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTenantServerCustomerRequestWithBody(server, "application/json", bodyReader)
}

// NewPostTenantServerCustomerRequestWithBody generates requests for PostTenantServerCustomer with any type of body
func NewPostTenantServerCustomerRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant-server/customer")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTenantServerCustomersRequest generates requests for GetTenantServerCustomers
func NewGetTenantServerCustomersRequest(server string, params *GetTenantServerCustomersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant-server/customers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostTenantServerGocardlessCancelByEnvironmentRequest calls the generic PostTenantServerGocardlessCancelByEnvironment builder with application/json body
func NewPostTenantServerGocardlessCancelByEnvironmentRequest(server string, environment string, body PostTenantServerGocardlessCancelByEnvironmentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTenantServerGocardlessCancelByEnvironmentRequestWithBody(server, environment, "application/json", bodyReader)
}

// NewPostTenantServerGocardlessCancelByEnvironmentRequestWithBody generates requests for PostTenantServerGocardlessCancelByEnvironment with any type of body
func NewPostTenantServerGocardlessCancelByEnvironmentRequestWithBody(server string, environment string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "environment", environment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant-server/gocardless/cancel/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostTenantServerStripeCancelByEnvironmentRequest calls the generic PostTenantServerStripeCancelByEnvironment builder with application/json body
func NewPostTenantServerStripeCancelByEnvironmentRequest(server string, environment string, body PostTenantServerStripeCancelByEnvironmentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTenantServerStripeCancelByEnvironmentRequestWithBody(server, environment, "application/json", bodyReader)
}

// NewPostTenantServerStripeCancelByEnvironmentRequestWithBody generates requests for PostTenantServerStripeCancelByEnvironment with any type of body
func NewPostTenantServerStripeCancelByEnvironmentRequestWithBody(server string, environment string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "environment", environment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant-server/stripe/cancel/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostTenantServerV2CustomerRequest calls the generic PostTenantServerV2Customer builder with application/json body
func NewPostTenantServerV2CustomerRequest(server string, body PostTenantServerV2CustomerJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTenantServerV2CustomerRequestWithBody(server, "application/json", bodyReader)
}

// NewPostTenantServerV2CustomerRequestWithBody generates requests for PostTenantServerV2Customer with any type of body
func NewPostTenantServerV2CustomerRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant-server/v2/customer")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostTenantEntitlementsActiveRequest calls the generic PostTenantEntitlementsActive builder with application/json body
func NewPostTenantEntitlementsActiveRequest(server string, body PostTenantEntitlementsActiveJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTenantEntitlementsActiveRequestWithBody(server, "application/json", bodyReader)
}

// NewPostTenantEntitlementsActiveRequestWithBody generates requests for PostTenantEntitlementsActive with any type of body
func NewPostTenantEntitlementsActiveRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/entitlements/active")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTenantEntitlementsByEnvironmentRequest generates requests for GetTenantEntitlementsByEnvironment
func NewGetTenantEntitlementsByEnvironmentRequest(server string, environment string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "environment", environment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/entitlements/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostTenantGocardlessBillingRequestFlowByEnvironmentRequest calls the generic PostTenantGocardlessBillingRequestFlowByEnvironment builder with application/json body
func NewPostTenantGocardlessBillingRequestFlowByEnvironmentRequest(server string, environment string, body PostTenantGocardlessBillingRequestFlowByEnvironmentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTenantGocardlessBillingRequestFlowByEnvironmentRequestWithBody(server, environment, "application/json", bodyReader)
}

// NewPostTenantGocardlessBillingRequestFlowByEnvironmentRequestWithBody generates requests for PostTenantGocardlessBillingRequestFlowByEnvironment with any type of body
func NewPostTenantGocardlessBillingRequestFlowByEnvironmentRequestWithBody(server string, environment string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "environment", environment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/gocardless/billing-request-flow/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostTenantIdentifyRequest calls the generic PostTenantIdentify builder with application/json body
func NewPostTenantIdentifyRequest(server string, body PostTenantIdentifyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTenantIdentifyRequestWithBody(server, "application/json", bodyReader)
}

// NewPostTenantIdentifyRequestWithBody generates requests for PostTenantIdentify with any type of body
func NewPostTenantIdentifyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/identify")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTenantProductsRequest generates requests for GetTenantProducts
func NewGetTenantProductsRequest(server string, params *GetTenantProductsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/products")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.ApiKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "api-key", *params.ApiKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("api-key", headerParam0)
		}

	}

	return req, nil
}

// NewPostTenantStripeCheckoutByEnvironmentRequest calls the generic PostTenantStripeCheckoutByEnvironment builder with application/json body
func NewPostTenantStripeCheckoutByEnvironmentRequest(server string, environment string, body PostTenantStripeCheckoutByEnvironmentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTenantStripeCheckoutByEnvironmentRequestWithBody(server, environment, "application/json", bodyReader)
}

// NewPostTenantStripeCheckoutByEnvironmentRequestWithBody generates requests for PostTenantStripeCheckoutByEnvironment with any type of body
func NewPostTenantStripeCheckoutByEnvironmentRequestWithBody(server string, environment string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "environment", environment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/stripe/checkout/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTenantStripeProductsByEnvironmentRequest generates requests for GetTenantStripeProductsByEnvironment
func NewGetTenantStripeProductsByEnvironmentRequest(server string, environment string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "environment", environment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/stripe/products/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostTenantSubscriptionsActiveRequest calls the generic PostTenantSubscriptionsActive builder with application/json body
func NewPostTenantSubscriptionsActiveRequest(server string, body PostTenantSubscriptionsActiveJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTenantSubscriptionsActiveRequestWithBody(server, "application/json", bodyReader)
}

// NewPostTenantSubscriptionsActiveRequestWithBody generates requests for PostTenantSubscriptionsActive with any type of body
func NewPostTenantSubscriptionsActiveRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/subscriptions/active")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostTenantServerCustomerWithBodyWithResponse request with any body
	PostTenantServerCustomerWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantServerCustomerResponse, error)

	PostTenantServerCustomerWithResponse(ctx context.Context, body PostTenantServerCustomerJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantServerCustomerResponse, error)

	// GetTenantServerCustomersWithResponse request
	GetTenantServerCustomersWithResponse(ctx context.Context, params *GetTenantServerCustomersParams, reqEditors ...RequestEditorFn) (*GetTenantServerCustomersResponse, error)

	// PostTenantServerGocardlessCancelByEnvironmentWithBodyWithResponse request with any body
	PostTenantServerGocardlessCancelByEnvironmentWithBodyWithResponse(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantServerGocardlessCancelByEnvironmentResponse, error)

	PostTenantServerGocardlessCancelByEnvironmentWithResponse(ctx context.Context, environment string, body PostTenantServerGocardlessCancelByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantServerGocardlessCancelByEnvironmentResponse, error)

	// PostTenantServerStripeCancelByEnvironmentWithBodyWithResponse request with any body
	PostTenantServerStripeCancelByEnvironmentWithBodyWithResponse(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantServerStripeCancelByEnvironmentResponse, error)

	PostTenantServerStripeCancelByEnvironmentWithResponse(ctx context.Context, environment string, body PostTenantServerStripeCancelByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantServerStripeCancelByEnvironmentResponse, error)

	// PostTenantServerV2CustomerWithBodyWithResponse request with any body
	PostTenantServerV2CustomerWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantServerV2CustomerResponse, error)

	PostTenantServerV2CustomerWithResponse(ctx context.Context, body PostTenantServerV2CustomerJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantServerV2CustomerResponse, error)

	// PostTenantEntitlementsActiveWithBodyWithResponse request with any body
	PostTenantEntitlementsActiveWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantEntitlementsActiveResponse, error)

	PostTenantEntitlementsActiveWithResponse(ctx context.Context, body PostTenantEntitlementsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantEntitlementsActiveResponse, error)

	// GetTenantEntitlementsByEnvironmentWithResponse request
	GetTenantEntitlementsByEnvironmentWithResponse(ctx context.Context, environment string, reqEditors ...RequestEditorFn) (*GetTenantEntitlementsByEnvironmentResponse, error)

	// PostTenantGocardlessBillingRequestFlowByEnvironmentWithBodyWithResponse request with any body
	PostTenantGocardlessBillingRequestFlowByEnvironmentWithBodyWithResponse(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantGocardlessBillingRequestFlowByEnvironmentResponse, error)

	PostTenantGocardlessBillingRequestFlowByEnvironmentWithResponse(ctx context.Context, environment string, body PostTenantGocardlessBillingRequestFlowByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantGocardlessBillingRequestFlowByEnvironmentResponse, error)

	// PostTenantIdentifyWithBodyWithResponse request with any body
	PostTenantIdentifyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantIdentifyResponse, error)

	PostTenantIdentifyWithResponse(ctx context.Context, body PostTenantIdentifyJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantIdentifyResponse, error)

	// GetTenantProductsWithResponse request
	GetTenantProductsWithResponse(ctx context.Context, params *GetTenantProductsParams, reqEditors ...RequestEditorFn) (*GetTenantProductsResponse, error)

	// PostTenantStripeCheckoutByEnvironmentWithBodyWithResponse request with any body
	PostTenantStripeCheckoutByEnvironmentWithBodyWithResponse(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantStripeCheckoutByEnvironmentResponse, error)

	PostTenantStripeCheckoutByEnvironmentWithResponse(ctx context.Context, environment string, body PostTenantStripeCheckoutByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantStripeCheckoutByEnvironmentResponse, error)

	// GetTenantStripeProductsByEnvironmentWithResponse request
	GetTenantStripeProductsByEnvironmentWithResponse(ctx context.Context, environment string, reqEditors ...RequestEditorFn) (*GetTenantStripeProductsByEnvironmentResponse, error)

	// PostTenantSubscriptionsActiveWithBodyWithResponse request with any body
	PostTenantSubscriptionsActiveWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantSubscriptionsActiveResponse, error)

	PostTenantSubscriptionsActiveWithResponse(ctx context.Context, body PostTenantSubscriptionsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantSubscriptionsActiveResponse, error)
}

type PostTenantServerCustomerResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *TenantServerGetCustomerResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PostTenantServerCustomerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTenantServerCustomerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTenantServerCustomersResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *ListCustomerResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetTenantServerCustomersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTenantServerCustomersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTenantServerGocardlessCancelByEnvironmentResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *TenantCancelGoCardlessSubscriptionResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PostTenantServerGocardlessCancelByEnvironmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTenantServerGocardlessCancelByEnvironmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTenantServerStripeCancelByEnvironmentResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *TenantCancelStripeSubscriptionResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PostTenantServerStripeCancelByEnvironmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTenantServerStripeCancelByEnvironmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTenantServerV2CustomerResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *TenantServerGetCustomerV2ResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PostTenantServerV2CustomerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTenantServerV2CustomerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTenantEntitlementsActiveResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *TenantActiveEntitlementsResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PostTenantEntitlementsActiveResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTenantEntitlementsActiveResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTenantEntitlementsByEnvironmentResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *TenantListEntitlementsResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetTenantEntitlementsByEnvironmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTenantEntitlementsByEnvironmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTenantGocardlessBillingRequestFlowByEnvironmentResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *TenantGoCardlessBillingRequestFlowResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PostTenantGocardlessBillingRequestFlowByEnvironmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTenantGocardlessBillingRequestFlowByEnvironmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTenantIdentifyResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *TenantIdentifyUserResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PostTenantIdentifyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTenantIdentifyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTenantProductsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *TenantListProductsResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetTenantProductsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTenantProductsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTenantStripeCheckoutByEnvironmentResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *TenantStripeCheckoutResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PostTenantStripeCheckoutByEnvironmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTenantStripeCheckoutByEnvironmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTenantStripeProductsByEnvironmentResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *TenantListStripeProductsResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetTenantStripeProductsByEnvironmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTenantStripeProductsByEnvironmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTenantSubscriptionsActiveResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *TenantActiveSubscriptionResponseBody
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PostTenantSubscriptionsActiveResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTenantSubscriptionsActiveResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostTenantServerCustomerWithBodyWithResponse request with arbitrary body returning *PostTenantServerCustomerResponse
func (c *ClientWithResponses) PostTenantServerCustomerWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantServerCustomerResponse, error) {
	rsp, err := c.PostTenantServerCustomerWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantServerCustomerResponse(rsp)
}

func (c *ClientWithResponses) PostTenantServerCustomerWithResponse(ctx context.Context, body PostTenantServerCustomerJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantServerCustomerResponse, error) {
	rsp, err := c.PostTenantServerCustomer(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantServerCustomerResponse(rsp)
}

// GetTenantServerCustomersWithResponse request returning *GetTenantServerCustomersResponse
func (c *ClientWithResponses) GetTenantServerCustomersWithResponse(ctx context.Context, params *GetTenantServerCustomersParams, reqEditors ...RequestEditorFn) (*GetTenantServerCustomersResponse, error) {
	rsp, err := c.GetTenantServerCustomers(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTenantServerCustomersResponse(rsp)
}

// PostTenantServerGocardlessCancelByEnvironmentWithBodyWithResponse request with arbitrary body returning *PostTenantServerGocardlessCancelByEnvironmentResponse
func (c *ClientWithResponses) PostTenantServerGocardlessCancelByEnvironmentWithBodyWithResponse(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantServerGocardlessCancelByEnvironmentResponse, error) {
	rsp, err := c.PostTenantServerGocardlessCancelByEnvironmentWithBody(ctx, environment, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantServerGocardlessCancelByEnvironmentResponse(rsp)
}

func (c *ClientWithResponses) PostTenantServerGocardlessCancelByEnvironmentWithResponse(ctx context.Context, environment string, body PostTenantServerGocardlessCancelByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantServerGocardlessCancelByEnvironmentResponse, error) {
	rsp, err := c.PostTenantServerGocardlessCancelByEnvironment(ctx, environment, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantServerGocardlessCancelByEnvironmentResponse(rsp)
}

// PostTenantServerStripeCancelByEnvironmentWithBodyWithResponse request with arbitrary body returning *PostTenantServerStripeCancelByEnvironmentResponse
func (c *ClientWithResponses) PostTenantServerStripeCancelByEnvironmentWithBodyWithResponse(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantServerStripeCancelByEnvironmentResponse, error) {
	rsp, err := c.PostTenantServerStripeCancelByEnvironmentWithBody(ctx, environment, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantServerStripeCancelByEnvironmentResponse(rsp)
}

func (c *ClientWithResponses) PostTenantServerStripeCancelByEnvironmentWithResponse(ctx context.Context, environment string, body PostTenantServerStripeCancelByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantServerStripeCancelByEnvironmentResponse, error) {
	rsp, err := c.PostTenantServerStripeCancelByEnvironment(ctx, environment, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantServerStripeCancelByEnvironmentResponse(rsp)
}

// PostTenantServerV2CustomerWithBodyWithResponse request with arbitrary body returning *PostTenantServerV2CustomerResponse
func (c *ClientWithResponses) PostTenantServerV2CustomerWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantServerV2CustomerResponse, error) {
	rsp, err := c.PostTenantServerV2CustomerWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantServerV2CustomerResponse(rsp)
}

func (c *ClientWithResponses) PostTenantServerV2CustomerWithResponse(ctx context.Context, body PostTenantServerV2CustomerJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantServerV2CustomerResponse, error) {
	rsp, err := c.PostTenantServerV2Customer(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantServerV2CustomerResponse(rsp)
}

// PostTenantEntitlementsActiveWithBodyWithResponse request with arbitrary body returning *PostTenantEntitlementsActiveResponse
func (c *ClientWithResponses) PostTenantEntitlementsActiveWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantEntitlementsActiveResponse, error) {
	rsp, err := c.PostTenantEntitlementsActiveWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantEntitlementsActiveResponse(rsp)
}

func (c *ClientWithResponses) PostTenantEntitlementsActiveWithResponse(ctx context.Context, body PostTenantEntitlementsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantEntitlementsActiveResponse, error) {
	rsp, err := c.PostTenantEntitlementsActive(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantEntitlementsActiveResponse(rsp)
}

// GetTenantEntitlementsByEnvironmentWithResponse request returning *GetTenantEntitlementsByEnvironmentResponse
func (c *ClientWithResponses) GetTenantEntitlementsByEnvironmentWithResponse(ctx context.Context, environment string, reqEditors ...RequestEditorFn) (*GetTenantEntitlementsByEnvironmentResponse, error) {
	rsp, err := c.GetTenantEntitlementsByEnvironment(ctx, environment, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTenantEntitlementsByEnvironmentResponse(rsp)
}

// PostTenantGocardlessBillingRequestFlowByEnvironmentWithBodyWithResponse request with arbitrary body returning *PostTenantGocardlessBillingRequestFlowByEnvironmentResponse
func (c *ClientWithResponses) PostTenantGocardlessBillingRequestFlowByEnvironmentWithBodyWithResponse(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantGocardlessBillingRequestFlowByEnvironmentResponse, error) {
	rsp, err := c.PostTenantGocardlessBillingRequestFlowByEnvironmentWithBody(ctx, environment, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantGocardlessBillingRequestFlowByEnvironmentResponse(rsp)
}

func (c *ClientWithResponses) PostTenantGocardlessBillingRequestFlowByEnvironmentWithResponse(ctx context.Context, environment string, body PostTenantGocardlessBillingRequestFlowByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantGocardlessBillingRequestFlowByEnvironmentResponse, error) {
	rsp, err := c.PostTenantGocardlessBillingRequestFlowByEnvironment(ctx, environment, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantGocardlessBillingRequestFlowByEnvironmentResponse(rsp)
}

// PostTenantIdentifyWithBodyWithResponse request with arbitrary body returning *PostTenantIdentifyResponse
func (c *ClientWithResponses) PostTenantIdentifyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantIdentifyResponse, error) {
	rsp, err := c.PostTenantIdentifyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantIdentifyResponse(rsp)
}

func (c *ClientWithResponses) PostTenantIdentifyWithResponse(ctx context.Context, body PostTenantIdentifyJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantIdentifyResponse, error) {
	rsp, err := c.PostTenantIdentify(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantIdentifyResponse(rsp)
}

// GetTenantProductsWithResponse request returning *GetTenantProductsResponse
func (c *ClientWithResponses) GetTenantProductsWithResponse(ctx context.Context, params *GetTenantProductsParams, reqEditors ...RequestEditorFn) (*GetTenantProductsResponse, error) {
	rsp, err := c.GetTenantProducts(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTenantProductsResponse(rsp)
}

// PostTenantStripeCheckoutByEnvironmentWithBodyWithResponse request with arbitrary body returning *PostTenantStripeCheckoutByEnvironmentResponse
func (c *ClientWithResponses) PostTenantStripeCheckoutByEnvironmentWithBodyWithResponse(ctx context.Context, environment string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantStripeCheckoutByEnvironmentResponse, error) {
	rsp, err := c.PostTenantStripeCheckoutByEnvironmentWithBody(ctx, environment, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantStripeCheckoutByEnvironmentResponse(rsp)
}

func (c *ClientWithResponses) PostTenantStripeCheckoutByEnvironmentWithResponse(ctx context.Context, environment string, body PostTenantStripeCheckoutByEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantStripeCheckoutByEnvironmentResponse, error) {
	rsp, err := c.PostTenantStripeCheckoutByEnvironment(ctx, environment, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantStripeCheckoutByEnvironmentResponse(rsp)
}

// GetTenantStripeProductsByEnvironmentWithResponse request returning *GetTenantStripeProductsByEnvironmentResponse
func (c *ClientWithResponses) GetTenantStripeProductsByEnvironmentWithResponse(ctx context.Context, environment string, reqEditors ...RequestEditorFn) (*GetTenantStripeProductsByEnvironmentResponse, error) {
	rsp, err := c.GetTenantStripeProductsByEnvironment(ctx, environment, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTenantStripeProductsByEnvironmentResponse(rsp)
}

// PostTenantSubscriptionsActiveWithBodyWithResponse request with arbitrary body returning *PostTenantSubscriptionsActiveResponse
func (c *ClientWithResponses) PostTenantSubscriptionsActiveWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantSubscriptionsActiveResponse, error) {
	rsp, err := c.PostTenantSubscriptionsActiveWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantSubscriptionsActiveResponse(rsp)
}

func (c *ClientWithResponses) PostTenantSubscriptionsActiveWithResponse(ctx context.Context, body PostTenantSubscriptionsActiveJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantSubscriptionsActiveResponse, error) {
	rsp, err := c.PostTenantSubscriptionsActive(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantSubscriptionsActiveResponse(rsp)
}

// ParsePostTenantServerCustomerResponse parses an HTTP response from a PostTenantServerCustomerWithResponse call
func ParsePostTenantServerCustomerResponse(rsp *http.Response) (*PostTenantServerCustomerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTenantServerCustomerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TenantServerGetCustomerResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetTenantServerCustomersResponse parses an HTTP response from a GetTenantServerCustomersWithResponse call
func ParseGetTenantServerCustomersResponse(rsp *http.Response) (*GetTenantServerCustomersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTenantServerCustomersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListCustomerResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePostTenantServerGocardlessCancelByEnvironmentResponse parses an HTTP response from a PostTenantServerGocardlessCancelByEnvironmentWithResponse call
func ParsePostTenantServerGocardlessCancelByEnvironmentResponse(rsp *http.Response) (*PostTenantServerGocardlessCancelByEnvironmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTenantServerGocardlessCancelByEnvironmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TenantCancelGoCardlessSubscriptionResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePostTenantServerStripeCancelByEnvironmentResponse parses an HTTP response from a PostTenantServerStripeCancelByEnvironmentWithResponse call
func ParsePostTenantServerStripeCancelByEnvironmentResponse(rsp *http.Response) (*PostTenantServerStripeCancelByEnvironmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTenantServerStripeCancelByEnvironmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TenantCancelStripeSubscriptionResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePostTenantServerV2CustomerResponse parses an HTTP response from a PostTenantServerV2CustomerWithResponse call
func ParsePostTenantServerV2CustomerResponse(rsp *http.Response) (*PostTenantServerV2CustomerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTenantServerV2CustomerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TenantServerGetCustomerV2ResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePostTenantEntitlementsActiveResponse parses an HTTP response from a PostTenantEntitlementsActiveWithResponse call
func ParsePostTenantEntitlementsActiveResponse(rsp *http.Response) (*PostTenantEntitlementsActiveResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTenantEntitlementsActiveResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TenantActiveEntitlementsResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetTenantEntitlementsByEnvironmentResponse parses an HTTP response from a GetTenantEntitlementsByEnvironmentWithResponse call
func ParseGetTenantEntitlementsByEnvironmentResponse(rsp *http.Response) (*GetTenantEntitlementsByEnvironmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTenantEntitlementsByEnvironmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TenantListEntitlementsResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePostTenantGocardlessBillingRequestFlowByEnvironmentResponse parses an HTTP response from a PostTenantGocardlessBillingRequestFlowByEnvironmentWithResponse call
func ParsePostTenantGocardlessBillingRequestFlowByEnvironmentResponse(rsp *http.Response) (*PostTenantGocardlessBillingRequestFlowByEnvironmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTenantGocardlessBillingRequestFlowByEnvironmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TenantGoCardlessBillingRequestFlowResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePostTenantIdentifyResponse parses an HTTP response from a PostTenantIdentifyWithResponse call
func ParsePostTenantIdentifyResponse(rsp *http.Response) (*PostTenantIdentifyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTenantIdentifyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TenantIdentifyUserResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetTenantProductsResponse parses an HTTP response from a GetTenantProductsWithResponse call
func ParseGetTenantProductsResponse(rsp *http.Response) (*GetTenantProductsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTenantProductsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TenantListProductsResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePostTenantStripeCheckoutByEnvironmentResponse parses an HTTP response from a PostTenantStripeCheckoutByEnvironmentWithResponse call
func ParsePostTenantStripeCheckoutByEnvironmentResponse(rsp *http.Response) (*PostTenantStripeCheckoutByEnvironmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTenantStripeCheckoutByEnvironmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TenantStripeCheckoutResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetTenantStripeProductsByEnvironmentResponse parses an HTTP response from a GetTenantStripeProductsByEnvironmentWithResponse call
func ParseGetTenantStripeProductsByEnvironmentResponse(rsp *http.Response) (*GetTenantStripeProductsByEnvironmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTenantStripeProductsByEnvironmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TenantListStripeProductsResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParsePostTenantSubscriptionsActiveResponse parses an HTTP response from a PostTenantSubscriptionsActiveWithResponse call
func ParsePostTenantSubscriptionsActiveResponse(rsp *http.Response) (*PostTenantSubscriptionsActiveResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTenantSubscriptionsActiveResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TenantActiveSubscriptionResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
